# Use new container infrastructure to enable caching
sudo: false

dist: bionic

language: generic

addons:
  apt:
    packages:
      - libsdl2-dev
      - libglu1-mesa-dev
      - libopengl-dev
      - freeglut3
      - freeglut3-dev
      - mesa-common-dev

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  # Build dependencies
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  # Build the package, its tests, and its docs and run the tests
  - stack --no-terminal test --haddock --no-haddock-deps

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack