name: imgui-haskell
version: 0.1.0.0
github: "githubuser/imgui-haskell"
license: BSD3
author: "Dominic Bou-Sa,ra"
maintainer: "dominic.bou.samra@gmail.com"
copyright: "2019 Dominic Bou-Samra"

build-type: Custom
extra-source-files:
  - README.md
  - external/**/*

# Metadata used when publishing your package
synopsis: Binding to the Dear Imgui graphical user interface library
category: Graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/imgui-haskell#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools: c2hs
  dependencies:
    - sdl2
  c-sources:
    - external/gl3w/src/gl3w.c
    - external/impl/src/imgui_impl_sdl.cpp
    - external/impl/src/imgui_impl_opengl3.cpp
  include-dirs:
    - external/gl3w/include
    - external/impl/include
    - external/cimgui
    - external/cimgui/imgui
  extra-libraries:
    - stdc++
    - SDL2
    - cimgui
  frameworks:
    - OpenGL
  cc-options:
    - -fPIC

executables:
  imgui-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - imgui-haskell
      - sdl2
      - linear
      - OpenGL
